services:
  api:
    build: .
    container_name: api-18
    restart: always
    ports:
      - "5004:5004"
    volumes:
      - .:/app
    working_dir: /app/api
    depends_on:
      - odoo
      - db
      - redis
    networks:
      - app-net-18

  celery_worker:
    build: .
    container_name: celery-worker-18
    command: celery -A app.celery_app worker --loglevel=DEBUG
    volumes:
      - .:/app
    working_dir: /app/api
    depends_on:
      - api
      - redis
      - odoo
    networks:
      - app-net-18

  celery_beat:
    build: .
    container_name: celery-beat-18
    command: celery -A app.celery_app beat --loglevel=DEBUG
    volumes:
      - .:/app
    working_dir: /app/api
    depends_on:
      - api
      - redis
      - odoo
    networks:
      - app-net-18

  redis:
    image: redis:latest
    container_name: redis-18
    ports:
      - "6380:6380"
    networks:
      - app-net-18

  odoo:
    image: odoo:latest
    container_name: odoo-18
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - odoo-data-18:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo_db
    networks:
      - app-net-18

  db:
    image: postgres:15
    container_name: db-18
    environment:
      - POSTGRES_DB=odoo_db
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5433:5432"
    volumes:
      - db-data-18:/var/lib/postgresql/data
    networks:
      - app-net-18

networks:
  app-net-18:

volumes:
  odoo-data-18:
  db-data-18:

