version: '3.9'

services:
  api:
    build: .
    container_name: api
    restart: always
    ports:
      - "5003:5003"
    volumes:
      - .:/app
    working_dir: /app/api
    depends_on:
      - odoo
      - db
      - redis
    networks:
      - app-net

  celery_worker:
    build: .
    container_name: celery-worker
    command: celery -A app.celery_app worker --loglevel=DEBUG
    volumes:
      - .:/app
    working_dir: /app/api
    depends_on:
      - api
      - redis
      - odoo
    networks:
      - app-net

  celery_beat:
    build: .
    container_name: celery-beat
    command: celery -A app.celery_app beat --loglevel=DEBUG
    volumes:
      - .:/app
    working_dir: /app/api
    depends_on:
      - api
      - redis
      - odoo
    networks:
      - app-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-net

  odoo:
    image: odoo:latest
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
      - DB_NAME=odoo_db
    networks:
      - app-net

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_DB=odoo_db
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-net

networks:
  app-net:

volumes:
  odoo-data:
  db-data:

